spring:
  data:
    mongodb:
      host: ${SPRING_MONGO_HOST}
      port: ${SPRING_MONGO_PORT}
      database: ${SPRING_MONGO_DATABASE}
      username: ${SPRING_MONGO_USER}
      password: ${SPRING_MONGO_PASSWORD}
